version: '3'
services:
  rtsp-stream-server:
    image: aler9/rtsp-simple-server:latest
    restart: always
    ports:
      - "8554:8554"
    volumes:
      - ${PWD}/mediamtx.yml:/mediamtx.yml

  ffmpeg:
    image: linuxserver/ffmpeg:latest
    restart: always
    volumes:
      - ${PWD}/h264.mp4:/h264.mp4
    command: ['-re', '-stream_loop', '-1', '-i', '/h264.mp4', '-f', 'rtsp', '-rtsp_transport', 'tcp', 'rtsp://rtsp-stream-server:8554/stream']

  yolo-python-rtsp:
    build:
      dockerfile: yolo-python-rtsp.dockerfile
    restart: no
    volumes:
      - ${PWD}/output:/home/yolo-python-rtsp/output
